# Generated by Django 5.1.2 on 2024-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_meal_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='total_cost',
            field=models.IntegerField(),
        ),
    ]
